config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  devise_for :users

  #userの注文、履歴が分かりやすいようにネスト
  resources :users do
    resources :addresses, only: [:edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_histories, only: [:index, :create]
  end



  #productの情報を取るためにcreateだけネスト
  resources :products, only:[:index, :show] do
    resources :cart_products, only: [:create, :destroy]
  end

  #cartproductの情報を取るためにcreateだけネスト
  resources :cart_products, only: [:index, :show, :destroy, :update] do
    resources :orders, only: [:create, :destroy]
  end

  resources :orders, only: [:show]


  namespace :admin do
    get "top" => "products#top"
    get "adasdfasdfasdfasdfksadfihsdfioehiepfahdvklasndfasknefpiaseipasefabsdklva" => "users#another", as:"another"
    resources :users
    resources :products
    resources :artist, only: [:new, :create]
    resources :genre, only: [:new, :create]
    resources :label, only: [:new, :create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artistname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    
    belongs_to :user
    belongs_to :product
    validates :product, presence: true, uniqueness: { scope: :user_id }
    
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :product

	has_many :songs, dependent: :destroy

	validates :cdname, presence: true

	accepts_nested_attributes_for :songs, allow_destroy: true

end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genrename,  presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/label.rb
class Label < ApplicationRecord
	validates :labelname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user

	has_many :order_histories
	accepts_nested_attributes_for :order_histories
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
    belongs_to :order

    belongs_to :product
    enum shipment_status: {発送準備中: 0, 発送済: 1, 到着済み: 2}

    def toggle_status!
        if "発送準備中"
            "発送済"
        elsif  "発送済"
            "到着済"
        else
            "到着済"
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
	def quantity
        cart_quantity = []
		self.stock_number.times do |i|
			cart_quantity += [i+1]
		end
        return cart_quantity
	end

	def self.search(search) #self.はProduct.を意味する
		if search
		  where(['productname LIKE ?', "%#{search}%"]) #検索とproductnameの部分一致を表示。
		else
		  Product.all #全て表示させる
	   end
	end


	has_many :cds, dependent: :destroy
	has_many :cart_products, dependent: :destroy
	has_many :order_histories

	validates :productname, presence: true
	validates :price, presence: true

	belongs_to :artist
	belongs_to :genre
	belongs_to :label

	attachment :image
	paginates_per 10

	accepts_nested_attributes_for :cds, allow_destroy: true
	accepts_nested_attributes_for :cart_products

	#enum
	
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd
	validates :songname, presence: true

end

app/models/user.rb
class User < ApplicationRecord
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
        devise :database_authenticatable, :registerable,
                :recoverable, :rememberable, :validatable

        has_many :orders

        has_many :addresses

        has_many :cart_products, dependent: :destroy

        accepts_nested_attributes_for :addresses, allow_destroy: true

        validates :name, presence: true
        validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
        validates :lastname_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

        VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

        # 電話番号の制御
        validates :tellnumber, presence: true, format: { with: VALID_PHONE_REGEX }

        #退会処理の記述
        acts_as_paranoid

        #ユーザーステータス
        enum user_status: {"アクティブ": 0, "退会済み": 1}
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController

  before_action :stock_set, only: [:create]

    def index
        @cart_products = current_user.cart_products.all
        @cart_product = current_user.cart_products.new
        @address = current_user.addresses.all
        @user = current_user.id
    end

    def create
        @cart_product = current_user.cart_products.new(cart_product_params)
        @cart_product.user_id = current_user.id
        @cart_product.product_id = params[:product_id]
        @cart_product.save
        redirect_to cart_products_path
    end

    def destroy
        cart_product = CartProduct.find_by(product_id: params[:product_id])
        cart_product.destroy
        redirect_to cart_products_path
    end

    private
    def cart_product_params
        params.require(:cart_product).permit(:purchase_number)
    end

    def stock_set
       @product = Product.find(params[:product_id])
       @stock_number = @product.stock_number
       if @stock_number == 0
           redirect_to product_path(@product)
       end
   end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_products/index.html.erb
    <% if @cart_product.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
            <ul>
                <% @cart_product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <h1>商品を購入しますか？</h1>
    <section class="product-box">
   
    <% @cart_products.each do |cart| %>
    <section class="left">
        <span class="product">

            <span class="image">
                <%= attachment_image_tag cart.product, :image, fallback:"no_image.png", size:"50x50" %>
            </span>
            <span class="text">
                <p class="song"><%= cart.product.productname %></p>
                <p class="artist"><%= cart.product.artist.artistname %></p>
                <p class="price">¥<%= cart.product.price %></p>
                <p class="price"><%= cart.purchase_number %>枚</p>
                <p class="delete"><%= link_to "カートから削除", product_cart_product_path(cart.product_id, cart.id), method: :delete, data:{confirm: "カートからこの商品を削除しますか？"}%></p>
            </span>
        </span>
    </section>
  
    <% end %>
    </section>
<%# カート内商品があるかどうかで分岐 %>
    <% if @cart_products.blank?  %>
        <p class="no_buy"><%= link_to "カートに商品を追加してください",products_path %></p>
        <% else %>

    <div class="cart_product">
        <%= link_to "注文する", cart_product_orders_path(@cart_products),method: :post, class:"buy1" %>
    </div>

        <p class="back_product"><%= link_to "商品一覧に戻る",products_path %></p>
        <% end %>


<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:center;
    }

    .product-box{
        margin-top:40px;
        overflow: hidden;
        position:rerative;
        zoom:1;
    }

    .left{
        width:50%;
        float:left;
        border-right:2px solid #222;
        display:flex;
    }

    .product{
        width:80%;
        height:190px;
        display:inline-block;
        margin-left:20%;
        justify-content: space-around;
        text-align:justify;
        clear:both;
    }

    .image{
        height:160px;
        width:160px;
        margin-top:2%;
        display:inline-block;
    }

    .text{
        float:right;
        width:60%;
    }

    .song{
        font-size:25px;
        text-align:center;
        white-space: pre;
    }

    .artist{
        font-size:18px;
        text-align:center;
    }

    .status{
        font-size:16px;
        text-align:center;
    }

    .price{
        font-size:20px;
        margin-top:10px;
        text-align:center;
    }

    .delete{
        width:43%;
        margin:0 auto;
        text-align:center;
        padding: 0.5em 1em;
        background:#ee9999;
        border-radius:10px;
    }

    .delete>a{
        color:#fff;
    }

    .buy{
        margin:40px auto;
        text-align:center;
        width:20%;
        padding: 0.5em 1em;
        background: skyblue;
        border-radius:10px;
    }

    .buy1{
        border:none;
        color:#fff;
        background:skyblue;
        font-size:17px;
    }

    .buy>a{
        color:#fff;
    }
    .no_buy{
        margin:40px auto;
        text-align:center;
        width:25%;
        padding: 0.5em 1em;
        background: red;
        border-radius:20px;
    }
    .no_buy>a {
        color:#fff;
    }

    .back_product{
        margin:40px auto;
        text-align:center;
        width:20%;
        padding: 0.5em 1em;
        background: purple;
        border-radius:10px;
    }
    .back_product>a{
        color:#fff;
    }
    .cart_product{
        margin:40px auto;
        text-align:center;
        width:20%;
        padding: 0.5em 1em;
        background: skyblue;
        border-radius:10px;
    }
    .cart_product>a{
        color:#fff;
    }
    .select_address {
       text-align: center;
    }

</style>