config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  devise_for :users

  #userの注文、履歴が分かりやすいようにネスト
  resources :users do
    resources :addresses, only: [:edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_histories, only: [:index, :create]
  end



  #productの情報を取るためにcreateだけネスト
  resources :products, only:[:index, :show] do
    resources :cart_products, only: [:create, :destroy]
  end

  #cartproductの情報を取るためにcreateだけネスト
  resources :cart_products, only: [:index, :show, :destroy, :update] do
    resources :orders, only: [:create, :destroy]
  end

  resources :orders, only: [:show]


  namespace :admin do
    get "top" => "products#top"
    get "adasdfasdfasdfasdfksadfihsdfioehiepfahdvklasndfasknefpiaseipasefabsdklva" => "users#another", as:"another"
    resources :users
    resources :products
    resources :artist, only: [:new, :create]
    resources :genre, only: [:new, :create]
    resources :label, only: [:new, :create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artistname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    
    belongs_to :user
    belongs_to :product
    validates :product, presence: true, uniqueness: { scope: :user_id }
    
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :product

	has_many :songs, dependent: :destroy

	validates :cdname, presence: true

	accepts_nested_attributes_for :songs, allow_destroy: true

end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genrename,  presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/label.rb
class Label < ApplicationRecord
	validates :labelname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user

	has_many :order_histories
	accepts_nested_attributes_for :order_histories
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
    belongs_to :order

    belongs_to :product
    enum shipment_status: {発送準備中: 0, 発送済: 1, 到着済み: 2}

    def toggle_status!
        if "発送準備中"
            "発送済"
        elsif  "発送済"
            "到着済"
        else
            "到着済"
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
	def quantity
        cart_quantity = []
		self.stock_number.times do |i|
			cart_quantity += [i+1]
		end
        return cart_quantity
	end

	def self.search(search) #self.はProduct.を意味する
		if search
		  where(['productname LIKE ?', "%#{search}%"]) #検索とproductnameの部分一致を表示。
		else
		  Product.all #全て表示させる
	   end
	end


	has_many :cds, dependent: :destroy
	has_many :cart_products, dependent: :destroy
	has_many :order_histories

	validates :productname, presence: true
	validates :price, presence: true

	belongs_to :artist
	belongs_to :genre
	belongs_to :label

	attachment :image
	paginates_per 10

	accepts_nested_attributes_for :cds, allow_destroy: true
	accepts_nested_attributes_for :cart_products

	#enum
	
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd
	validates :songname, presence: true

end

app/models/user.rb
class User < ApplicationRecord
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
        devise :database_authenticatable, :registerable,
                :recoverable, :rememberable, :validatable

        has_many :orders

        has_many :addresses

        has_many :cart_products, dependent: :destroy

        accepts_nested_attributes_for :addresses, allow_destroy: true

        validates :name, presence: true
        validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
        validates :lastname_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

        VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

        # 電話番号の制御
        validates :tellnumber, presence: true, format: { with: VALID_PHONE_REGEX }

        #退会処理の記述
        acts_as_paranoid

        #ユーザーステータス
        enum user_status: {"アクティブ": 0, "退会済み": 1}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :admin_users

    def top
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to admin_products_path
        else
            flash.now[:product] = "商品の保存に失敗しました。正しい入力を行なってください"
            render "new"
        end
    end

    def index

        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
        @cart_product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        @product.update(product_params)
        redirect_to admin_product_path(params[:id])
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
    end

    private

    def product_params
        params.require(:product).permit(:label_id,:genre_id, :artist_id, :stock_number, :productname, :sale_status, :price, :image, cds_attributes: [:id, :cdname, :_destroy, songs_attributes: [:id, :songname, :song_number, :_destroy]])
    end

    def admin_users
        redirect_to products_path unless current_user.admin?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

	def index
		@songs = Song.all.order(created_at: :desc).page(params[:page]).per(10)
		@artists= Artist.all.order(created_at: :desc).page(params[:page]).per(10)
		@products = Product.search(params[:search]).page(params[:page]).per(10)
	end

	def show
		@product = Product.find(params[:id])

		if user_signed_in?
			@cart = current_user.cart_products.new
		end
	end
	class ProductSearchForm
		include ActiveModel::Model

		attr_accessor  :productname

		def search
			rel = Product
			rel = rel.where( productname: productname ) if productname.present?
		
			rel
		end
	end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_cd_fields.html.erb
<p class="nested-fields">
	CD:<%= f.text_field :cdname %><br>
	<%= link_to_remove_association 'CDを削除', f %>
		<%= link_to_add_association '曲を追加', f, :songs %>
		<%= f.fields_for :songs do |song| %>
			<%= render 'song_fields', f: song %>
		<% end %>
</p>

app/views/admin/products/_song_fields.html.erb
<p class="nested-fields">
	曲：<%= f.text_field :songname %>
	<%= link_to_remove_association '曲を削除', f %>
</p>

app/views/admin/products/edit.html.erb
<body>
    <h1>商品の編集</h1>
    <section class="add-box">
    <div class="left">
        <p class="add-text">画像</p><br>
        <p class="add-text">商品名</p><br>
        <p class="add-text">価格</p><br>
        <p class="add-text">画像を追加</p><br>
        <p class="add-text">販売中・販売中止</p><br>
        <p class="add-text">在庫数</p><br>
        <p class="add-text">アーティスト名</p><br>
        <p class="add-text">ジャンル名</p><br>
        <p class="add-text">レーベル名</p>
    </div>
    <div class="right">
        <p class="form"><%= attachment_image_tag @product, :image, fallback:"no_image.png", size:"50x50" %></p>

    <%= nested_form_for(@product, url: admin_product_path, method: :PUT) do |product| %>
    <p class="form"><%= product.text_field :productname, :placeholder => "商品名"  %></p> <br class="s">
    <p class="form"><%= product.number_field :price, :placeholder => "値段" %></p><br>
    <p class="form"><%= product.attachment_field :image, format: "jpeg", size: "100x100", fallback: 'no_image.png' %></p><br>
    <p class="form">
        <label><%= product.radio_button :sale_status, '販売中' %> 販売中  </label>
        <label><%= product.radio_button :sale_status, '販売停止中' %>  販売停止中 </label>
    </p><br><br>
    <p class=“form”><%= product.number_field :stock_number%></p><br>

    <p class="form"><%= product.collection_select :artist_id, Artist.all, :id, :artistname %>
    <%= link_to '⇦にアーティスト名が無い場合はこちら', new_admin_artist_path %></p><br>

    <p class="form"><%= product.collection_select :genre_id, Genre.all, :id, :genrename %>
    <%= link_to '⇦にジャンルが無い場合はこちら', new_admin_genre_path %></p><br>

    <p class="form"><%= product.collection_select :label_id, Label.all, :id, :labelname %>
    <%= link_to '⇦にレーベルが無い場合はこちら', new_admin_label_path %></p><br>


                <%= product.fields_for :cds do |cd| %>
                    <p class="nested-fields">
                        CD名: <%= cd.text_field :cdname %><br>
                        <%= link_to_remove_association 'CDを削除', cd %>
                            <%= link_to_add_association '曲を追加', cd, :songs %>
                            <%= cd.fields_for :songs do |song| %>
                                <p class="nested-fields">
                                    曲名: <%= song.text_field :songname %>
                                    <%= link_to_remove_association '曲を削除', song %>
                                </p>
                            <% end %>
                    </p>
                <% end %>
    </div>
    <%= product.submit "商品を更新する", :class=>"btn"%>
    <% end %>
    </section>
</body>
</html>

<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:center;
    }

    .add-box{
        margin-top:40px;
    }

    .left{
        width:35%;
        float:left;
        margin-left:15%;
    }

    .right{
        width:50%;
        float:right;
    }

    input[type="text"] {
        width: 300px;
        height: 40px;
    }

    input[type="number"] {
        width: 300px;
        height: 40px;
    }

    .add-text{
        font-size:23px;
        text-align:center;
        margin-top:10px;
    }

    .form{
        height:40px;
    }

    .form:nth-child(7){
        padding-top:16px;
    }

    .form:nth-child(9){
        margin-top:20px;
    }

    .form:nth-child(11){
        padding-top:5px;
    }

    .form:nth-child(13){
        padding-top:5px;
    }

    .form:nth-child(15){
        padding-top:8px;
    }

    .btn {
        background-color:#ccc;
        width: 250px;
        height: 70px;
        margin-left:40%;
        font-size:20px;
        margin-bottom:50px;
    }

    
</style>

app/views/admin/products/index.html.erb
    <h1>CD一覧</h1>
    <section class="product-box">
    <% @products.each do |product| %>
    <section class="left">
        <span class="product">
            <%= link_to admin_product_path(product.id) do %>
                <span class="image">
                 <%= attachment_image_tag product, :image, fallback:"no_image.png", size:"50x50" %>
                </span>
            <% end %>
            <span class="text">
                <p class="song"><%= product.productname %></p>
                <p class="artist"><%= product.artist.artistname %></p>
                <p class="price">¥<%= product.price %></p>
                <p class="artist">在庫数:<%= product.stock_number %>枚</p>
                <%= link_to admin_product_path(product.id) do %>
                        <% if product.stock_number > 0 %>
                            <div class="status-box">
                                <p class="status">
                                    販売中
                                </p>
                            </div>
                                <% else %>
                            <div class="status-box1">
                                <p class="status">
                                    品切
                                </p>
                        <% end %>
                    </div>
                    </div>
                <% end %>
            </span>
        </span>
    </section>
    <% end %>
    </section>


<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:center;
    }

    p{
        margin:0;
    }

    .product-box{
        margin-top:40px;
        height:auto;
        overflow: hidden;
        position:rerative;
        zoom:1;
    }

    .left{
        width:50%;
        float:left;
        border-right:2px solid #222;
        display:flex;
    }

    

    .product{
        width:80%;
        height:190px;
        display:flex;
        justify-content: space-around;
        text-align:justify;
        margin-left:13%;
        clear:both;
    }

    .image{
        height:160px;
        width:160px;
        margin-top:2%;
        display:inline-block;
    }

    .text{
        float:right;
        width:60%;
    }

    .song{
        font-size:25px;
        text-align:center;
        overflow: scroll;
        white-space: pre;
    }

    .artist{
        font-size:18px;
        text-align:center;
    }

    .status{
        font-size:16px;
        text-align:center;
    }

    .price{
        font-size:20px;
        text-align:center;
    }

    .status-box{
        width:40%;
        margin:0 auto;
        padding: 0.5em 1em;
        background: -moz-linear-gradient(#ffb03c, #ff708d);
        background: -webkit-linear-gradient(#ffb03c, #ff708d);
        background: linear-gradient(to right, #ffb03c, #ff708d);
        border-radius:70%;
        color: #FFF;
    }
    .status-box1{
        width:40%;
        margin:0 auto;
        padding: 0.5em 1em;
        background: red;
        border-radius:70%;
        color: #FFF;
    }
    </style>

app/views/admin/products/new.html.erb
<h3 class="flash_product"><%= flash.now[:product] %></h3>

<div class="product_content">
    <h1>商品の追加</h1>
    <section class="add-box">
    <%= form_for(@product, url:"/admin/products") do |f| %>

        <div class="left">
            <p class="add-text">商品名</p><br>
            <p class="add-text">価格</p><br>
            <p class="add-text">画像を追加</p><br>
            <p class="add-text">販売中・販売中止</p><br>
            <p class="add-text">在庫数</p>
            <p class="add-text">アーティスト名</p><br>
            <p class="add-text">ジャンル名</p><br>
            <p class="add-text">レーベル名</p>
            <p class="add-text">CDを追加</p>
        </div>

        <div class="right">
        <p class="form"><%= f.text_field :productname, :placeholder => "商品名"  %></p><br>
        <p class="form"><%= f.number_field :price, :placeholder => "値段" %></p><br>
        <p class="form"><%= f.attachment_field :image, format: 'jpeg', size: "100x100", fallback:"no_image.png" %></p><br>
        <p class="form">
            <label><%= f.radio_button :sale_status, '販売中' %> 販売中  </label>
            <label><%= f.radio_button :sale_status, '販売停止中' %> 販売停止中  </label>
        </p><br>


            <%= f.select :stock_number, options_for_select((0..100).to_a) %><br><br>


            <p class="form"><%= f.collection_select :artist_id, Artist.all, :id, :artistname %>
            <%= link_to '⇦にアーティスト名が無い場合はこちら', new_admin_artist_path %></p><br>

            <p class="form"><%= f.collection_select :genre_id, Genre.all, :id, :genrename %>
            <%= link_to '⇦にジャンルが無い場合はこちら', new_admin_genre_path %></p><br>

            <p class="form"><%= f.collection_select :label_id, Label.all, :id, :labelname %>
            <%= link_to '⇦にレーベルが無い場合はこちら', new_admin_label_path %></p><br>

            <%# cdの情報 %>
            <p class="form">
                <%= link_to_add_association 'CDを追加', f, :cds %>
                <%= f.fields_for :cds do |cd| %>
                    <%= render 'cd_fields', f: cd %>
                <% end %>
            </p>
        </div>

        <%= f.submit "商品を追加する", :class=>"btn"%>

    <% end %>
    </section>
</div>

<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:center;
    }

    .add-box{
        margin-top:40px;
    }

    .left{
        width:35%;
        float:left;
        margin-left:15%;
    }

    .right{
        width:50%;
        float:right;
    }

    input[type="text"] {
        width: 300px;
        height: 40px;
    }

    input[type="number"] {
        width: 300px;
        height: 40px;
    }

    .add-text{
        font-size:23px;
        text-align:center;
        margin-top:10px;
    }

    .form{
        height:40px;
    }

    .form:nth-child(7){
        padding-top:16px;
    }

    .form:nth-child(9){
        margin-top:20px;
    }

    .form:nth-child(11){
        padding-top:5px;
    }

    .form:nth-child(13){
        padding-top:5px;
    }

    .form:nth-child(15){
        padding-top:8px;
    }

    .btn {
        background-color:#ccc;
        width: 250px;
        height: 70px;
        margin-left:40%;
        font-size:20px;
        margin-bottom:50px;
    }
    .flash_product{
        text-align: center;
        color:red;
        font-size: 25px;
    }
    .product_content{
        margin-top:70px;
    }

    .add_fields{
        background:#65f0f2;
        color:black;
        padding:5px 5px;
        border-radius:5px;
    }

    .remove_fields{
        background:#78dca5;
        color:black;
        padding:5px;
        border-radius:5px;
    }
</style>

app/views/admin/products/top.html.erb
    <div class="to_s"><%= link_to "商品一覧", admin_products_path %></div>
    <div class="to_u"><%= link_to "ユーザー一覧", admin_users_path %></div>
<style>
    .to_s{
        margin-top:5%;
        width:70%;
        height:120px;
        margin-left:15%;
        font-size:40px;
        padding: 0.7em 1em;
        background: #008080;
        border-radius:15px;
        text-align:center;
    }

    .to_s>a{
        color:#fff;
    }

    .to_u{
        margin-top:5%;
        width:70%;
        height:120px;
        margin-left:15%;
        font-size:40px;
        padding: 0.7em 1em;
        background: #8b0000;
        border-radius:15px;
        text-align:center;
    }

    .to_u>a{
        color:#fff;
    }

</style>

app/views/products/index.html.erb
    <h1>CD一覧</h1>
    <div class="search-box">
    <%= form_tag(products_path, :method => "get") do %>
    <%= text_field_tag :search, params[:search],class:"search_field" %> 
    <%= submit_tag "商品名検索" ,:productname => nil ,class:"submit"%> 
    <% end %> 
    </div>

    <section class="product-box">
        <% @products.each do |product| %>
            <section class="left">
                <span class="product">
                    <%= link_to product_path(product.id) do %>
                        <span class="image">
                            <%= attachment_image_tag product, :image, fallback:"no_image.png", size:"50x50" %>
                        </span>
                    <% end %>
                    <span class="text">
                        <p class="song"><%= product.productname %></p>
                        <p class="artist"><%= product.artist.artistname %></p>
                            <%= link_to product_path(product.id) do %>
                                <% if product.stock_number > 0 %>
                                    <div class="status-box">
                                        <p class="status">
                                            販売中
                                        </p>
                                    </div>
                                <% else %>
                                    <div class="status-box1">
                                        <p class="status">
                                            品切
                                        </p>
                                    </div>
                                <% end %>
                            <% end %>
                        <p class="price">¥<%= product.price %></p>
                        <p class="price">在庫数:<%= product.stock_number %>枚</p>
                    </span>
                </span>
            </section>
        <% end %>
    </section>
    <div class="paging"><%= paginate @products %>  
    </div>

<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:center;
    }

    p{
        margin:0;
    }

    .product-box{
        margin-top:40px;
        height:auto;
        overflow: hidden;
        position:rerative;
        zoom:1;
    }

    .left{
        width:50%;
        float:left;
        border-right:2px solid #222;
        display:flex;
    }

    

    .product{
        width:80%;
        height:190px;
        display:flex;
        justify-content: space-around;
        text-align:justify;
        margin-left:13%;
        clear:both;
    }

    .image{
        height:160px;
        width:160px;
        margin-top:2%;
        display:inline-block;
    }

    .text{
        float:right;
        width:60%;
    }

    .song{
        font-size:25px;
        text-align:center;
        overflow: scroll;
        white-space: pre;
    }

    .artist{
        font-size:18px;
        text-align:center;
        white-space: pre;
    }

    .status{
        font-size:16px;
        text-align:center;
    }

    .price{
        font-size:20px;
        text-align:center;
    }

    .status-box{
        width:40%;
        margin:0 auto;
        padding: 0.5em 1em;
        background: -moz-linear-gradient(#ffb03c, #ff708d);
        background: -webkit-linear-gradient(#ffb03c, #ff708d);
        background: linear-gradient(to right, #ffb03c, #ff708d);
        border-radius:70%;
        color: #FFF;
    }
        .status-box1{
        width:40%;
        margin:0 auto;
        padding: 0.5em 1em;
        background: red;
        border-radius:70%;
        color: #FFF;
    }

    .paging{
        text-align:center;
        height: 60px;
    }

    .search-box{
        margin:0 auto;
        width:80%;
        height:90px;
        padding:2%;
    }

    input[type="text"]{
        width:75%;
        height:40px;
        border:1px #999 solid;
        border-radius:10px;
        margin-left:10%;
    }

    .submit{
        width:10%;
        height:30px;
        border-radius:10px;
    }


</style>

app/views/products/show.html.erb
<section class="around-border">
    <div class="text_of_top"><p style="color:white;">商品詳細</p>
    </div>
    <section class="product_info">
        <div class="image-box">
            <%= attachment_image_tag @product, :image, fallback:"no_image.png", size:"50x50" %>
        </div>
        <div class="product-text">
            <div class="text-top">
                <p class="product-name"><b><%= @product.productname %></b></p>
                <p class="product-artist"><%= @product.artist.artistname %></p><br>
                <p class="product-label">レーベル：<%= @product.label.labelname %></p>
            </div>
            <div class="text-bottom">
                <% if @product.stock_number > 0 %>
                    <div class="status">
                        <b>販売中</b>
                    </div>
                <% else %>
                    <div class="none">
                        <b>品切</b>
                    </div>
                <% end %>
                <div class="quantity"><b>在庫残り<%= @product.stock_number %>枚</b></div>
            </div>
        </div>
        <div class="cart-buy-box">
            <div class="price-box">
                <p class="prise-text"><b>販売価格（税込）</b></p>
                <p class="product-prise">¥<%= @product.price %></p>
            </div>
            <% if user_signed_in?%>
                <% if current_user.admin?%>
                    <div class="btn-box">
                        <div class="btn-p"><%= link_to "編集", edit_admin_product_path(@product.id), class: 'btn-primary'%></div>
                        <div class="btn-d"><%= link_to "削除", admin_product_path(@product.id), method: :delete, data:{confirm: "商品削除しますか？"}, class: 'btn-danger' %></div>
                    </div>
                <% else %>
                <% if @product.stock_number > 0 %>
                    <%= form_for @cart,url:product_cart_products_path(@product) do |f| %>
                    <p class="buy_quantity">購入数</p>
                    <%= f.select :purchase_number, @product.quantity%><br>
                    <%= f.submit "カートに追加",class:"btn2" %></div>
                <% end %>
            <% else %>
                <p class="sorry">申し訳ございません、品切れです。</p>
            <% end %>
            <% end %>
            <% else %>
                <div class="log-box">
                <p class="status2"><%= link_to '会員登録 ', new_user_registration_path %></p>
                <p class="status1"><%= link_to 'ログイン ',new_user_session_path %></p>
                </div>
            <% end %>
        </div>
        
    </section>
    <div class="genre-box"><p class="product-genre"><%= @product.genre.genrename %></p></div>
    <section class="cd-info">
        <div class="cd">
        <p>CD内容</p>
        </div>
        
        <% @product.cds.each do |song_cd| %>
        <div class="cd-in">
                <div class="cd-name">
                <b class="product-item"><b><%= song_cd.cdname %></b></p>
                </div>
                <div class="song-box">
                <div class="title-box"><p class="title">タイトル</p></div>
                <% song_cd.songs.each_with_index do |song, i| %>
                    <div class="song-name">
                    <p class="song"><%= i + 1 %>. <%= song.songname %></p>
                    </div>
                <% end %>
                </div>
        </div>

        <% end %>
        
    </section>   
    <%= link_to "戻る", products_path, class: 'btn'%>
 </section>

        
    
        
   
    

<style>
    *{
        margin:0;
        padding:0;
        box-sizing:border-box;
    }

    h1{
        text-align:left;
    }

    .around-border{
        margin:5% 6% 5% 6%;
        border:1px solid #ddd;
    }

    .product_info{
        padding:25px 35px;;
    }

    .text_of_top{
        background-color:black;
        height:5%;
        width:38%;
        font-size:18px;
        padding:0.4%;
        margin-top:1%;
        margin-left:-1%;
    }

    .text_of_top>p{
        margin:0;
    }

    .image-box{
        width:280px;
        height:280px;
        margin-right:35px;
        display:inline-block;
        float:left;
    }

    .image-box>img{
        width:280px;
        height:280px;
    }

    .product-text{
        width:45%;
        display:inline-block;
    }

    .text-top{
        height:200px;
    }

    .product-name{
        font-size:24px;
    }

    .product-artist{
        font-size:20px;
    }

    .text-bottom{
        height:80px;
        border-top:1px solid #ddd;
        border-bottom:1px solid #ddd;
    }

    .status{
        font-size:19px;
    }

    .none{
        font-size:19px;
        color:red;
    }

    .quantity{
        font-size:16px;
    }

    .cart-buy-box{
        width:22%;
        height:260px;
        background-color:#d3e7ff;
        display:inline-block;
        float:right;
    }

    .prise-text{
        font-size:18px;
        margin:15px;

    }

    .product-prise{
        font-size:28px;
        margin-right:19px;
        float:right;
        margin-left:63%;
    }

    .buy_quantity{
        font-size:19px;
        margin-left:40px;
        float:left;
        margin-top:12px;
    }

    #cart_product_purchase_number{
        border:solid 1px #ddd;
        width:30px;
        height:25px;
        float:right;
        margin-top:12px;
        font-size:15px;
        margin-right:50px;
    }

    .btn2{
        width:190px;
        height:40px;
        background-color:red;
        border-radius:20px;
        color:white;
        font-size:20px;
        margin:30px 0 0 20px;
    }

    .genre-box{
        width:160px;
        height:30px;
        background:black;
        color:white;
        margin-left:100px;
        font-size:22px;
        text-align:center;
    }

    .cd{
        background:black;
        color:white;
        margin:100px 80px 0 80px;
        height:30px;
        font-size:22px;
        padding-left:20px;
    }

    .cd-in{
        border:solid 1px #ddd;
        margin:30px 90px 0 90px;
    }

    .btn{
        background:black;
        padding:5px 10px 5px 10px;
        font-size:20px;
        border-radius:9px;
        margin:50px 0 40px 47%;
        color:white;
    }

    .cd-name{
        background:#808080;
        color:white;
        font-size:15px;
        height:30px;
        padding-top:4px;
        padding-left:12px;
    }

    .song-box{
        margin:10px;
    }

    .title-box{
        background:gray;
        color:white;
        height:38px;
        font-size:14px;
        padding:9px 0 0 10px;
    }

    .song-name{
        font-size:16px;
        padding:8px 0 0 12px;
        font-weight:normal;
        height:40px;
    }

    .song-name:nth-child(odd){
        background:#e6e6e6;
    }

    .song-name:nth-child(even){
        background:#ccc;
    }

    .status1{
        padding:8px 0 0 47px;
        background:#888;
        border-radius:20px;
        width:160px;
        height:40px;
        margin:30px 0 0 13%;
        font-size:17px;
    }

    .status1>a{
        color:white;
    }

    .status2{
        padding:8px 0 0 46px;
        background:#111;
        border-radius:20px;
        width:160px;
        height:40px;
        margin:80px 0 0 13%;
        font-size:17px;
    }

    .status2>a{
        color:white;
    }

    .price-box{
        width:100%;
        height:100px;
        display:inline-block;
    }

    .btn-box{
        width:100%;
        height:150px;
        display:inline-block;
    }
    
    .btn-p{
        margin:30px 0 0 57px;
        font-size:20px;
    }

    .btn-primary{
        padding:10px 40px;
        font-size:20px;
        border-radius:10px;
    }

    .btn-d{
        margin:40px 0 0 57px;
        font-size:20px;
    }

    .btn-danger{
        font-size:20px;
        padding:10px 40px;
        border-radius:10px;
    }
</style>