config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  devise_for :users

  #userの注文、履歴が分かりやすいようにネスト
  resources :users do
    resources :addresses, only: [:edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_histories, only: [:index, :create]
  end



  #productの情報を取るためにcreateだけネスト
  resources :products, only:[:index, :show] do
    resources :cart_products, only: [:create, :destroy]
  end

  #cartproductの情報を取るためにcreateだけネスト
  resources :cart_products, only: [:index, :show, :destroy, :update] do
    resources :orders, only: [:create, :destroy]
  end

  resources :orders, only: [:show]


  namespace :admin do
    get "top" => "products#top"
    get "adasdfasdfasdfasdfksadfihsdfioehiepfahdvklasndfasknefpiaseipasefabsdklva" => "users#another", as:"another"
    resources :users
    resources :products
    resources :artist, only: [:new, :create]
    resources :genre, only: [:new, :create]
    resources :label, only: [:new, :create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artistname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    
    belongs_to :user
    belongs_to :product
    validates :product, presence: true, uniqueness: { scope: :user_id }
    
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :product

	has_many :songs, dependent: :destroy

	validates :cdname, presence: true

	accepts_nested_attributes_for :songs, allow_destroy: true

end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genrename,  presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/label.rb
class Label < ApplicationRecord
	validates :labelname, presence: true
	has_many :products
	accepts_nested_attributes_for :products
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user

	has_many :order_histories
	accepts_nested_attributes_for :order_histories
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
    belongs_to :order

    belongs_to :product
    enum shipment_status: {発送準備中: 0, 発送済: 1, 到着済み: 2}

    def toggle_status!
        if "発送準備中"
            "発送済"
        elsif  "発送済"
            "到着済"
        else
            "到着済"
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
	def quantity
        cart_quantity = []
		self.stock_number.times do |i|
			cart_quantity += [i+1]
		end
        return cart_quantity
	end

	def self.search(search) #self.はProduct.を意味する
		if search
		  where(['productname LIKE ?', "%#{search}%"]) #検索とproductnameの部分一致を表示。
		else
		  Product.all #全て表示させる
	   end
	end


	has_many :cds, dependent: :destroy
	has_many :cart_products, dependent: :destroy
	has_many :order_histories

	validates :productname, presence: true
	validates :price, presence: true

	belongs_to :artist
	belongs_to :genre
	belongs_to :label

	attachment :image
	paginates_per 10

	accepts_nested_attributes_for :cds, allow_destroy: true
	accepts_nested_attributes_for :cart_products

	#enum
	
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd
	validates :songname, presence: true

end

app/models/user.rb
class User < ApplicationRecord
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
        devise :database_authenticatable, :registerable,
                :recoverable, :rememberable, :validatable

        has_many :orders

        has_many :addresses

        has_many :cart_products, dependent: :destroy

        accepts_nested_attributes_for :addresses, allow_destroy: true

        validates :name, presence: true
        validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
        validates :lastname_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}

        VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

        # 電話番号の制御
        validates :tellnumber, presence: true, format: { with: VALID_PHONE_REGEX }

        #退会処理の記述
        acts_as_paranoid

        #ユーザーステータス
        enum user_status: {"アクティブ": 0, "退会済み": 1}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :admin_users, except: [:another]
    def another
    end

    def index
        @users = User.with_deleted
    end

    def show
        @user = User.with_deleted.find(params[:id])
    end

    def  edit
    end

    def update
    end

    def destroy
    end

    private
    def admin_users
        redirect_to products_path unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @users = User.all
    end

    def edit
        @user = User.find(params[:id])
        @addresses = Address.all
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(params[:id])
        else
            flash[:alert] = "住所の保存に失敗しました！"
            render "edit"
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to products_path
    end

    private
    def user_params
        params.require(:user).permit(:email, :name,:lastname, :name_kana,:lastname_kana, :tellnumber, addresses_attributes: [:id, :prefecture, :municipality, :building, :address_number, :_destroy])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/another.html.erb
管理者 ID, email => pp@pp, pass=> aaaaaa



<div class="sign_in_form">
    <div class="sign_in_content">
    <h2>管理者ログインページ</h2><br><br>
<%= form_for(:user, :url => session_path(:user)) do |f| %>

      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", :placeholder => "例）aaa@gmail.com" %>
      </div>

      <div class="field">
        <%= f.label :パスワード %><br />
        <%= f.password_field :password, autocomplete: "current-password", :placeholder => "パスワードを入力してください" %>
      </div>


      <div class="actions">
        <%= f.submit "ログイン",class:"btn btn-success" %>
      </div><br>
    <% end %>
  <br>

  </div>
</div>

<style>
    .sign_in_form {
    margin: 50px auto 50px auto;
    text-align: center;
    border :inset;
    width: 800px;
    height: 600px
  }
    .sign_in_content {
      padding-top: 40px;
    }
</style>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
<div class="users">
<% @users.each do |f| %>
    <div class="user-box">
        <% if f.deleted_at? %>
            <div class="left-top">退会済み</div>
        <% else %>
            <% if f.admin? %>
            <div class="left-top1">管理者</div>
            <% else %>
            <div class="left-top2">アクティブユーザー</div>
            <% end %>
        <% end %>
        <div class="info-left">
            <p>ユーザ名：</p>
            <p>メールアドレス：</p>
            <p>電話番号：</p>
        </div>
        <div class="info-center">
            <p><%= f.name %><%= f.lastname %></p>
            <p><%= f.email %></p>
            <p><%= f.tellnumber %></p>
        </div>
            <% if f.admin? %>
            <% else %>
                <div class="info-right">
                <%= link_to admin_user_path(f) do %>
                <div class="info-right2">
                    <p>詳細</p>
                </div>
            <% end %>
        <% end %>
        </div>
    </div>
<% end %>
</div>

<style>

h1{
    text-align:center;
}

.users{
    margin-top:5%;
}

.user-box{
    width:70%;
    height:150px;
    margin:5% auto;
    background:#ddd;
    font-size:20px;
    display:flex;
}

.info-left{
    width:40%;
    height:150px;
    text-align:right;
}

.info-left>p{
    margin-top:4%;
}

.info-center>p{
    margin-top:4%;
}

.info-center{
    width:50%;
    height:150px;
    padding-left:10%;
}

.info-right{
    width:10%;
    height:150px;
    background:#777;
    text-align:center;
    text-decoration:none;
}

.info-right2{
    height:150px;
    padding-top:65%;
    background:#777;
}

.info-right2 > p{
    text-decoration:none;
    color:#fff;
}

.right-top{
    height:75px;
}

.right-bottom{
    height:75%;
}

.left-top{
    position:absolute;
    width:15%;
    background: red;
    border-radius:5%;
    text-align:center;
    color:white;
}
.left-top1{
    position:absolute;
    width:15%;
    background: green;
    border-radius:5%;
    text-align:center;
    color:white;
}
.left-top2{
    position:absolute;
    width:15%;
    background: #6787cd;
    border-radius:5%;
    text-align:center;
    color:white;
}

</style>

app/views/admin/users/show.html.erb
<div class= "user_information">
    <h2>ユーザー情報</h2>
    <div class="user_name">ユーザー名：<%= @user.name %><%= @user.lastname %></div><br>
    <div class="user_email">E-mail：　<%= @user.email %></div><br>
    <div class="user_email">電話番号：　<%= @user.tellnumber %></div><br>

    <% @user.addresses.each_with_index do |address, i| %>
        <h3>住所<%= i + 1 %></h3>
        <div>郵便番号：　<%= address.address_number %></div>
        <div>都道府県：　<%= address.prefecture %></div>
        <div>市区町村：　<%= address.municipality %></div>
        <div>建物：　<%= address.building %></div>
    <% end %>


    <% if @user.deleted_at? %>
        退会したユーザーです
    <% else %>
        <%= link_to "ユーザー情報の変更", edit_user_path(@user), class:"btn btn-success" %><br><br>
        <%= link_to "ユーザーの削除",user_path(@user),method: :delete, class:"btn btn-danger",data: {confirm: "ユーザーを削除しますか？"}  %>
    <% end %>
        <%= link_to "購入履歴",user_order_histories_path(@user.id),class:"btn btn-danger" %>


</div>
<div class="border"></div>


<style>

.user_information {
    text-align: center;
    margin: 40px auto 0 auto;
}

.user_name {
    display: inline-block;
    margin-top: 10px;
    font-size: 27px;
}
.user_email {
    display: inline-block;
    margin: 10px;
    font-size: 25px;
}
.btn btn-danger {
    margin-right:20px;
}

.border{
    border: solid 2px gray;
    margin:30px auto;
    width: 700px;
}
</style>

app/views/users/_address_fields.html.erb
<div class="user_edit">
    <div class="border-edit">
		<div class="nested-fields">
			<div class="field">
				<div class="field">
					<%= f.label :郵便番号 %><br>
				<%= f.text_field :address_number %>
				</div>
				<div class="field">
					<%= f.label :都道府県 %><br>
				<%= f.text_field :prefecture %>
				</div>
				<div class="field">
					<%= f.label :市区町村 %><br>
				<%= f.text_field :municipality %>
				</div>
				<div class="field">
					<%= f.label :建物 %><br>
				<%= f.text_field :building %>
				</div>
			</div>
			<div class="links">
				<%= link_to_remove_association '住所を削除', f %>
				<br><%= f.submit "update user information", class: 'btn btn-success' %>
			</div>
		</div>
	</div>
</div>
	<style>
	.user_edit {
    text-align: center;
    margin:0 auto;
    width: 700px;
    height: 500px;
}

	</style>

app/views/users/edit.html.erb
<h2 class="address_message"><%= flash[:alert] %></h2>

<h2 class="address_message"><%= flash[:address]%></h2>
<div class="user_edit">
  <div class="border-edit">
    <%= form_for @user do |f| %>
          <div class= "field">
            <%= f.label :苗字 %><br>
            <%= f.text_field :name, :placeholder => "例）志位出意" %>
          </div>

          <div class= "field">
            <%= f.label :名前 %><br>
            <%= f.text_field :lastname, :placeholder => "例）太朗" %>
          </div>

          <div class= "field">
            <%= f.label :フリガナ（苗字） %><br>
            <%= f.text_field :name_kana, :placeholder => "例）シイテイ" %>
          </div>

          <div class= "field">
            <%= f.label :フリガナ（名前） %><br>
            <%= f.text_field :lastname_kana, :placeholder => "例）タロウ" %>
          </div>

          <div class= "field">
            <%= f.label :電話番号 %><br>
            <%= f.text_field :tellnumber, :placeholder => "ハイフンなしで入力してください" %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", :placeholder => "例）aaa@gmail.com" %>
          </div>
            <%= f.submit "変更する",class:"btn btn-success" %>

          <div class="links">
            <%= link_to_add_association '住所を追加', f, :addresses, id:"address_nest",class:"btn btn-danger" %>
          </div>

          <%= f.fields_for :addresses, @user.addresses do |a| %>
            <%= render 'address_fields', f: a %>
          <% end %>

          <div class="actions">
          </div>
    <% end %>
    </div>
</div>

<style>
.user_edit {
  text-align: center;
}

.user_edit-ex {
    text-align: center;
    border: solid 2px gray;
    width: 700px;
    height: 800px;
}
.address_message{
  text-align:center;
  color:red;
}

</style>

app/views/users/show.html.erb
<div class= "user_information">
    <h2>ユーザー情報</h2>
    <div class="user_name">ユーザー名：<%= @user.name %><%= @user.lastname %></div><br>
    <div class="user_name">カタカナ：<%= @user.name_kana %><%= @user.lastname_kana %></div><br>

    <div class="user_email">E-mail：<%= @user.email %></div><br>
    <div class="user_email">電話番号：<%= @user.tellnumber %></div><br>

    <% @user.addresses.each_with_index do |address, i| %>
        <h3>住所<%= i + 1 %></h3>
        <div>郵便番号：<%= address.address_number %></div>
        <div>都道府県：<%= address.prefecture %></div>
        <div>市区町村：<%= address.municipality %></div>
        <div>建物：<%= address.building %></div>
        <%= link_to '住所を編集', edit_user_address_path(current_user.id, address.id) %>
        <%= link_to '住所を削除', user_address_path(current_user.id, address.id) , method: :delete, data: {confirm: 'この住所を削除しますか？'} %><br>
    <% end %><br>

    <%= link_to "ユーザー情報の変更", edit_user_path(@user), class:"btn btn-success" %><br><br>

    <% if current_user.admin? %>
        <%= link_to "ユーザーの削除",user_path(@user),method: :delete, class:"btn btn-danger",data: {confirm: "ユーザーを削除しますか？"}  %>
    <% else %>
        <%= link_to "退会",user_path(@user),method: :delete, class:"btn btn-danger",data: {confirm: "退会しますか？"} %>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
        <%= link_to "log out",destroy_user_session_path,class:"btn btn-primary", data: {confirm: "ログアウトしますか？"}, method: :delete %>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
        <%= link_to "購入履歴",user_order_histories_path(current_user.id),class:"btn btn-danger" %>
    <% end %>
</div>
<div class="border"></div>
<style>

.user_information {
    text-align: center;
    margin: 40px auto 0 auto;
}

.user_name {
    display: inline-block;
    margin-top: 10px;
    font-size: 27px;
}
.user_email {
    display: inline-block;
    margin: 10px;
    font-size: 25px;
}
.btn btn-danger {
    margin-right:20px;
}

.border{
    border: solid 2px gray;
    margin:30px auto;
    width: 700px;
}
</style>